### ISSUE TITLE
Error: Cannot find module 'simple-syntax-highlighter' | Nuxt Generate | Vue 2 

### ISSUE THREAD

**Issue by rylax** [antoniandre/simple-syntax-highlighter#17]
Hey folks!

I am able to successfully add to `ssh-pre` component to my Nuxt/Vue2 page and everything renders perfectly. Unfortunately, after a hard refresh of the page or simply doing a `npm run generate` I get thrown the following error:

```
Error: Cannot find module 'simple-syntax-highlighter' from 'xxxx'
```

Anyone an idea on what could be the issue?

**Comment by antoniandre** [comment]
Hi, sorry I'm late to the party.

simple-syntax-highlighter is using the DOM to syntax highlight.
In order to make this work with Nuxt, you need to prevent it from running server side.
Here is one way you can do so directly in your component:

```vue
<template>
  <client-only>
      <component :is="'sshpre'" language="js" label="Javascript">
          const i = 3;
          // Some more Javascript content.
      </component>
  </client-only>
</template>

<script>
export default {
  components: { sshpre: () => import('simple-syntax-highlighter') }

```

If you need this multiple time. you can do this once, in a component that you can reuse.

Hope it makes sense!
Please reopen if not solved :)
