### ISSUE TITLE
Safari does not support negative lookbehind

### ISSUE THREAD

**Issue by JoeMGomes** [antoniandre/simple-syntax-highlighter#20]
Found this issue randomly because my version of this package wasn't locked at 1.4.8. The latest version is not working in webkit browsers, throwing `Syntax Error: Invalid regular expression: invalid group specifier name`

https://github.com/antoniandre/simple-syntax-highlighter/blob/ca4091af4c7acfecff1a27b39634734c785c24b1/src/components/simple-syntax-highlighter.vue#L51

**Comment by antoniandre** [comment]
Hi @JoeMGomes, SorryI missed this issue earlier.
Have you tried updating your OS (in order to update Safari to the latest)?
It should be supported since last March https://caniuse.com/js-regexp-lookbehind, I was waiting for this to happen for some time! :)
Let me know if that doesn't solve your issue, we can reopen with a reproduction link!
